version: '3.8'
services:
  apacheweb:
    build: ./web
    container_name: apacheweb
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    env_file:
      - .env
    depends_on: 
      - db
    ports:
      - 8080:80
    networks:
      - net_lamp
  db:
    build: ./db
    container_name: db
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    env_file:
      - .env
    networks:
      - net_lamp
networks:
  net_lamp: