version: '3.8'
services:

  vote:
    image: voting-app:vote-1.0.0
    container_name: vote-app
    environment:
      - VIRTUAL_HOST=vote.192.168.33.10.sslip.io
      - VIRTUAL_HOST=80
    ports: 
      - 5000:80
    depends_on:
      - redis  
    networks:
      - frontend
      - backend

  result:
    image: voting-app:resul-1.0.0
    container_name: result-app
    environment:
      - VIRTUAL_HOST=result.192.168.33.10.sslip.io
      - VIRTUAL_HOST=80  
    ports:
      - 5001:80
    depends_on:
      - db
    networks:
      - frontend
      - backend

  worker:
    image: voting-app:worker-1.0.0
    container_name: worker-app
    depends_on:
      - db
      - redis
    networks:
    - backend

  bd:
    image: postgres:15-alpine
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data 
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:6.17
    container_name: pgadmin
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=secret123
      - PGADMIN_DEFAULT_PORT=80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - backend    
    depends_on:
      - db

  redis:
    image: redis:alpine
    container_name: redis
    volumes: 
      - redis-data:/data
    networks:
      - backend

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
    - frontend  


volumes:
  db-data:
  redis-data:
  pgadmin-data:

networks:
  frontend:
  backend:  